var VIEWDIRECTION;
(function (VIEWDIRECTION) {
    VIEWDIRECTION[VIEWDIRECTION["NONE"] = 0] = "NONE";
    VIEWDIRECTION[VIEWDIRECTION["LEFT"] = 1] = "LEFT";
    VIEWDIRECTION[VIEWDIRECTION["TOP"] = 2] = "TOP";
    VIEWDIRECTION[VIEWDIRECTION["RIGHT"] = 3] = "RIGHT";
    VIEWDIRECTION[VIEWDIRECTION["BOTTOM"] = 4] = "BOTTOM";
})(VIEWDIRECTION || (VIEWDIRECTION = {}));
//# sourceMappingURL=GameConst.js.map